swagger: '2.0'

info:
  version: "1.0.0"
  title: Cog Memory Service

basePath: "/v1/services/memory/1.0.0"

definitions:
  memory_value:
    description: |
      A value to be stored in memory, added to memory, or retrieved
      from memory.

      Though this is formally declared as a `string` type, it can
      actually be any valid JSON value (object, list, number, etc.)
    type: string

paths:
  /{key}:
    get:
      description: |
        Retrieve the current value stored under `key`
      parameters:
        - name: key
          in: path
          description: the memory key to retrieve
          required: true
          type: string
      responses:
        "200":
          description: The current value stored under `key`
          schema:
            $ref: '#/definitions/memory_value'
        "404":
          description: The key was not found
    put:
      description: |
        Set a value for `key`
      parameters:
        - name: key
          in: path
          description: the key to operate on
          required: true
          type: string
        - name: data
          in: body
          description: Value to set for `key`
          required: true
          schema:
            $ref: '#/definitions/memory_value'
      responses:
        "200":
          description: The resulting value of `key`
    post:
      description: |
        Perform a memory operation
      parameters:
        - name: key
          in: path
          description: the key to operate on
          required: true
          type: string
        - name: operation
          in: body
          description: Operation to perform on `key`
          required: true
          schema:
            type: object
            required:
              - op
              - value
            properties:
              op:
                type: string
                enum:
                  - accum
                  - join
              value:
                $ref: '#/definitions/memory_value'
      responses:
        "200":
          description: The resulting value of `key`
        "422":
          description: The operation requires a list to operate on.
    delete:
      description: |
        Delete current value stored under `key`
      parameters:
        - name: key
          in: path
          description: the key to operate on
          required: true
          type: string
      responses:
        "200":
          description: The last value of `key` prior to deletion
