common:
  environment:
    - COG_API_URL_HOST=${COG_HOST}
    - COG_API_URL_PORT=80
    - COG_TRIGGER_URL_HOST=${COG_HOST}
    - COG_TRIGGER_URL_PORT=4001
    - COG_SERVICE_URL_HOST=${COG_HOST}
    - COG_SERVICE_URL_PORT=4002
