#
# Notes:
#
# The following variables must be set in the shell that docker-compose
# is executed from:
#
# POSTGRES_USER, POSTGRES_PASSWORD, SLACK_API_TOKEN
#
# In addition, a TAG variable may be defined. If present, it will be appended
# to the Docker image names that are used for Cog and Relay. It should begin
# with a colon (:), i.e. TAG=:0.2.1-dev
#
# $ docker-compose up
#

postgres:
  image: postgres:9.5
  environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
cog:
  image: operable/cog${TAG}
  environment:
    - COG_MQTT_HOST=0.0.0.0
    - DATABASE_URL=ecto://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/cog
    - COG_ADAPTER=${COG_ADAPTER}
    - SLACK_API_TOKEN=${SLACK_API_TOKEN}
    - HIPCHAT_API_TOKEN=${HIPCHAT_API_TOKEN}
    - HIPCHAT_MENTION_NAME=${HIPCHAT_MENTION_NAME}
    - HIPCHAT_XMPP_NICKNAME=${HIPCHAT_XMPP_NICKNAME}
    - HIPCHAT_XMPP_SERVER=${HIPCHAT_XMPP_SERVER}
    - HIPCHAT_XMPP_ROOMS=${HIPCHAT_XMPP_ROOMS}
    - HIPCHAT_XMPP_PORT=${HIPCHAT_XMPP_PORT}
    - HIPCHAT_XMPP_JID=${HIPCHAT_XMPP_JID}
    - HIPCHAT_XMPP_PASSWORD=${HIPCHAT_XMPP_PASSWORD}
    - ERL_FLAGS=-smp enable
  links:
    - postgres:localhost
  ports:
    - 80:4000
    - 1883
  entrypoint: /home/operable/cog/scripts/docker-start
